name: Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Tap brew cask
      run: |
        brew tap caskroom/cask
        brew update
    - name: Install dependencies
      run: |
        brew cask install perforce
        brew install fish
    - name: Install BP4O
      run: |
        brew install ./bp4o.rb
        brew test ./bp4o.rb
